services:
  - type: web
    name: apollo-server-sample
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false && yarn run build
    startCommand: yarn run start -H 0.0.0.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: BUGSNAG_API_KEY
        value:
databases:
  - name: apollo-server-sample
    plan: starter
    databaseName: apollo
    user: admin
